services:
    App\Admin\LecturerAdmin:
        arguments: [~, App\Entity\Lecturer, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Lecturer, group: Lecturer }

    App\Admin\UserAdmin:
        arguments: [~, App\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: User, group: User }
        calls:
            - [setPasswordEncoder, ['@Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface']]

    App\Admin\DisciplineAdmin:
        arguments: [~, App\Entity\Discipline, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Discipline, group: Discipline }

    App\Admin\SpecialtyAdmin:
        arguments: [~, App\Entity\Specialty, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Specialty, group: Specialty }

    App\Admin\FacultyAdmin:
        arguments: [~, App\Entity\Faculty, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Faculty, group: Faculty }

    App\Admin\RoomsAdmin:
        arguments: [~, App\Entity\Rooms, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Rooms, group: Rooms }

    App\Admin\AcademicTitleAdmin:
        arguments: [~, App\Entity\AcademicTitle, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: AcademicTitle, group: Lecturer }

    App\Admin\ScientificTitleAdmin:
        arguments: [~, App\Entity\ScientificTitle, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: ScientificTitle, group: Lecturer }

    App\Admin\GroupsAdmin:
        arguments: [~, App\Entity\Groups, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Groups, group: Groups }

    App\Admin\SubGroupsAdmin:
        arguments: [~, App\Entity\SubGroups, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: SubGroups, group: Groups }
