services:
    App\Admin\LecturerAdmin:
        arguments: [~, App\Entity\Lecturer, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Lecturer, group: Lecturer }

    App\Admin\UserAdmin:
        arguments: [~, App\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: User, group: User }
        calls:
            - [setPasswordEncoder, ['@Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface']]

    App\Admin\DisciplineAdmin:
        arguments: [~, App\Entity\Discipline, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Discipline, group: Discipline }

    App\Admin\SpecialtyAdmin:
        arguments: [~, App\Entity\Specialty, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Specialty, group: Specialty }
