sonata_admin:
    title: 'TU Scheduler Admin'
    options:
        title_mode: single_text
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
